package com.feryaeljustice.mirailink.domain.model.user

import com.feryaeljustice.mirailink.domain.model.catalog.Anime
import com.feryaeljustice.mirailink.domain.model.catalog.Game
import kotlinx.serialization.Serializable

@Serializable
data class User(
    val id: String,
    val username: String,
    val nickname: String,
    val email: String?,
    val phoneNumber: String?,
    val bio: String?,
    val gender: String?,
    val birthdate: String?,
    val photos: List<UserPhoto> = emptyList(),
    val games: List<Game>,
    val animes: List<Anime>,
    val fcmToken: String? = "",
    val residenceCountryId: String? = null,
    val residenceRegionId: String? = null,
    val residenceCityId: String? = null,
    val residenceCity: String? = null,
    val residenceRegion: String? = null,
    val residenceCountryCode: String? = null,
    val residenceCountry: String? = null,
    val residenceLatitude: Double? = null,
    val residenceLongitude: Double? = null,
    val currentLatitude: Double? = null,
    val currentLongitude: Double? = null,
    val distanceKm: Double? = null,
    val isTraveler: Boolean = false,
    val profession: String? = null,
    val religionId: String? = null,
    val religion: String? = null,
    val zodiacSignId: String? = null,
    val zodiacSign: String? = null,
    val politicalStanceId: String? = null,
    val politicalStance: String? = null,
    val smokingHabitId: String? = null,
    val smokingHabit: String? = null,
    val drinkingHabitId: String? = null,
    val drinkingHabit: String? = null,
    val sexualOrientationId: String? = null,
    val sexualOrientation: String? = null,
    val educationLevelId: String? = null,
    val educationLevel: String? = null,
    val relationshipGoalIds: List<String> = emptyList(),
    val relationshipGoals: List<String> = emptyList(),
    val familyOptionIds: List<String> = emptyList(),
    val familyOptions: List<String> = emptyList(),
    val spokenLanguageIds: List<String> = emptyList(),
    val spokenLanguages: List<String> = emptyList(),
    val prompts: List<GamerPromptAnswer> = emptyList(),
)
